# def imprimir_mensaje():
#     print("Mensaje Especial")
#     print(" ESTOY APRENDIENDO FUNCIONES")


# imprimir_mensaje() 
# imprimir_mensaje()
# imprimir_mensaje()



# def conversacion(mensaje):
#     print("Hola")
#     print("Como estas?")
#     print(mensaje)
#     print("Adios")


# opcion = int(input("Elige una opcion (1, 2, 3): "))
# if opcion == 1:
#     conversacion("elegiste la opcion 1")
# elif opcion == 2:
#    conversacion("elegiste la opcion 2")
# elif opcion == 3:
#     conversacion("elegiste la opcion 3")
# else:
#     print("Elige una opcion correcta")



def suma(a, b):
    print ("Se suman dos numeros")
    resultado = a + b
    return resultado

sumatoria = suma(1, 4)
print(sumatoria)